# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch: { }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache native dependencies
        uses: actions/cache@v2
        with:
          path: |
            odgf
            .ogdf-build
          key: ${{ runner.os }}-deps
      - name: Install native dependencies
        run: sudo apt-get install -y libtheora-dev libgtest-dev libsfml-dev libosmesa6-dev
      - name: Build natives
        uses: gradle/gradle-build-action@v2
        with:
          arguments: make
      - name: Build java
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileJava compileTestJava
      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkstyleMain

